### ISSUE TITLE
When I run the code I get an SSL error

### ISSUE THREAD

**Issue by pooyanjamshidi** [softsys4ai-lab/perfBugMiner#1]
This might be related to `urllib2`. I run the script with `python2.7`.
```
Pooyans-MacBook-Pro:perfBugMiner pjamshidi$ python github_issues_api_get_closed_issues.py 
EXTRACTING: https://api.github.com/repos/tensorflow/tensorflow/issues?page=1&state=closed&client_id=xxx&client_secret=yyy
Traceback (most recent call last):
  File "github_issues_api_get_closed_issues.py", line 59, in <module>
    content = GetJsonFromAPI(url)
  File "/Users/pjamshidi/devrepo/perfBugMiner/config.py", line 38, in GetJsonFromAPI
    response = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

**Comment by kevinren12138** [comment]
This issue may cause the certificate authentication. I import SSL in the config file to avoid the certificate authentication, hope the issue could be solved in this way.

**Comment by ZhangXiaoAlisia** [comment]
hi, I have seen your sess.run() problem. I also encounted this. When I use sess.run(), then the kernel died in spyder. Have you solved this problem? If so, could you tell m ethe solution?
